-- =====================================================
-- Table tags
-- =====================================================
CREATE TABLE odr.tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	code VARCHAR(55) UNIQUE,
	name VARCHAR(55) NOT NULL,
	description TEXT,
	created TIMESTAMPTZ DEFAULT now(),
	updated TIMESTAMPTZ
);

-- =====================================================
-- Table orders
-- =====================================================
CREATE TABLE odr.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status BIGINT REFERENCES odr.tags(id),
    code VARCHAR(55) UNIQUE,
    checkout_cred TEXT NOT NULL,
    total_price DECIMAL(10,2),
    sub_info JSONB,
	created TIMESTAMPTZ DEFAULT now(),
	updated TIMESTAMPTZ
);

-- =====================================================
-- Table payments
-- =====================================================
CREATE TABLE odr.payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status BIGINT REFERENCES odr.tags(id),
    method_cred TEXT NOT NULL,
    provider_req BIGINT REFERENCES odr.tags(id),
    order_id BIGINT REFERENCES odr.orders(id),
    created TIMESTAMPTZ DEFAULT now(),
    updated TIMESTAMPTZ
);

-- =====================================================
-- Table method_provider
-- =====================================================
CREATE TABLE odr.method_provider (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    method BIGINT REFERENCES odr.tags(id),
    provider BIGINT REFERENCES odr.tags(id),
    url VARCHAR(500) NOT NULL,
    requirement JSONB NOT NULL
);
