-- =====================================================
-- Table credentials
-- =====================================================
CREATE TABLE idp.credentials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject TEXT UNIQUE,
    created TIMESTAMPTZ DEFAULT now(),
    updated TIMESTAMPTZ
);

-- =====================================================
-- Table scopes
-- =====================================================
CREATE TABLE idp.scopes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource VARCHAR(55) NOT NULL,
    action VARCHAR(55) NOT NULL,
    UNIQUE(resource, action),
    type BOOLEAN DEFAULT TRUE,
    created TIMESTAMPTZ DEFAULT now(),
    updated TIMESTAMPTZ
);

-- =====================================================
-- Table audiences
-- =====================================================
CREATE TABLE idp.audiences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(55) UNIQUE,
    type BOOLEAN DEFAULT TRUE,
    created TIMESTAMPTZ DEFAULT now(),
    updated TIMESTAMPTZ
);

-- =====================================================
-- Table credential_scope
-- =====================================================
CREATE TABLE idp.credential_scope (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    credential_id BIGINT REFERENCES idp.credentials(id),
    scope_id BIGINT REFERENCES idp.scopes(id)
);

-- =====================================================
-- Table credential_audience
-- =====================================================
CREATE TABLE idp.credential_audience (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    credential_id BIGINT REFERENCES idp.credentials(id),
    audience_id BIGINT REFERENCES idp.audiences(id)
);
